server {
    listen 80;

    location /seco2/api/ {
        proxy_pass http://backend:8002/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /seco2/ {
        alias /usr/share/nginx/html/;
        try_files $uri $uri/ /seco2/index.html;
    }

    location = /seco2 {
        return 301 /seco2/;
    }
}
