server {
    listen 80;

    location /seco1/api/ {
        proxy_pass http://backend:8001/api/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /seco1/ {
        alias /usr/share/nginx/html/;
        try_files $uri $uri/ /seco1/index.html;
    }

    location = /seco1 {
        return 301 /seco1/;
    }
}
